version: '3.8'
services:
  demo:
    container_name: nillion
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.10-slim
        ARG DEBIAN_FRONTEND="noninteractive"
        SHELL ["/bin/bash", "-o", "pipefail", "-xe", "-c"]
        RUN apt update; \
            apt install -y --no-install-recommends \
                jq; \
            apt clean; \
            rm -rf /var/lib/apt/lists/*; \
            pip install --upgrade pip; \
            groupadd -r nillion; \
            useradd -rm -g nillion nillion;
        USER nillion
    network_mode: 'bridge'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - NILLION_SDK_ROOT=/sdk
    volumes:
      - '$PWD/..:/host'
      - $NILLION_SDK_ROOT:/sdk
    working_dir: /host
    command:
      - /bin/bash
      - '-c'
      - |
        source ./utils.sh
        check_for_sdk_root
        install_nada_dsl
        pushd permissions
        ./bootstrap-local-environment.sh
